// lib/services/report_export_service.dart
// Service untuk export laporan ke PDF dan Excel

import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import 'package:open_file/open_file.dart';
import '../models/report.dart';

class ReportExportService {
  static final currencyFormatter = NumberFormat.currency(
    locale: 'id_ID',
    symbol: 'Rp ',
    decimalDigits: 0,
  );

  // ===== PDF EXPORT =====

  static Future<File> exportToPdf(SavingsReport report) async {
    final pdf = pw.Document();

    // Add pages
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          _buildPdfHeader(report),
          pw.SizedBox(height: 20),
          _buildPdfSummary(report),
          pw.SizedBox(height: 20),
          _buildPdfGoals(report),
          pw.SizedBox(height: 20),
          if (report.achievements.isNotEmpty) ...[
            _buildPdfAchievements(report),
            pw.SizedBox(height: 20),
          ],
          if (report.badges.isNotEmpty) ...[
            _buildPdfBadges(report),
            pw.SizedBox(height: 20),
          ],
          if (report.tips.isNotEmpty) ...[
            _buildPdfTips(report),
            pw.SizedBox(height: 20),
          ],
          if (report.monthlyBreakdown.isNotEmpty)
            _buildPdfMonthlyBreakdown(report),
          pw.SizedBox(height: 20),
          if (report.transactions.isNotEmpty) _buildPdfTransactions(report),
        ],
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 20),
          child: pw.Text(
            'Halaman ${context.pageNumber} dari ${context.pagesCount} - Generated by GoalMoney',
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
        ),
      ),
    );

    // Save file
    final directory = await getApplicationDocumentsDirectory();
    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    final file = File('${directory.path}/Laporan_GoalMoney_$timestamp.pdf');
    await file.writeAsBytes(await pdf.save());

    return file;
  }

  static pw.Widget _buildPdfHeader(SavingsReport report) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColors.green100,
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'GoalMoney',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.green800,
                ),
              ),
              pw.Text(
                report.reportDate,
                style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
              ),
            ],
          ),
          pw.SizedBox(height: 10),
          pw.Text(
            report.reportTitle,
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 5),
          pw.Text(
            'Periode: ${report.period.startDate} - ${report.period.endDate}',
            style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfSummary(SavingsReport report) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Ringkasan Tabungan',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 15),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: [
              _buildPdfStatBox(
                'Total Goal',
                '${report.summary.totalGoals}',
                PdfColors.blue,
              ),
              _buildPdfStatBox(
                'Selesai',
                '${report.summary.completedGoals}',
                PdfColors.green,
              ),
              _buildPdfStatBox(
                'Aktif',
                '${report.summary.activeGoals}',
                PdfColors.orange,
              ),
            ],
          ),
          pw.SizedBox(height: 15),
          pw.Divider(),
          pw.SizedBox(height: 10),
          _buildPdfRow(
            'Total Ditabung',
            currencyFormatter.format(report.summary.totalSaved),
          ),
          _buildPdfRow(
            'Total Target',
            currencyFormatter.format(report.summary.totalTarget),
          ),
          _buildPdfRow(
            'Sisa Target',
            currencyFormatter.format(
              report.summary.totalTarget - report.summary.totalSaved,
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Container(
            height: 15,
            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: pw.BorderRadius.circular(5),
            ),
            child: pw.ClipRRect(
              horizontalRadius: 5,
              verticalRadius: 5,
              child: pw.Container(
                width: (report.summary.overallProgress / 100) * 400,
                color: PdfColors.green,
              ),
            ),
          ),
          pw.SizedBox(height: 5),
          pw.Center(
            child: pw.Text(
              'Progress: ${report.summary.overallProgress.toStringAsFixed(1)}%',
              style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfStatBox(
    String label,
    String value,
    PdfColor color,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 20, vertical: 10),
      decoration: pw.BoxDecoration(
        color: color.shade(100),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        children: [
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
              color: color,
            ),
          ),
          pw.SizedBox(height: 5),
          pw.Text(label, style: pw.TextStyle(fontSize: 10, color: color)),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 12)),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfGoals(SavingsReport report) {
    if (report.goals.isEmpty) return pw.SizedBox();

    return pw.Container(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Detail Goal Tabungan',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            columnWidths: {
              0: const pw.FlexColumnWidth(3),
              1: const pw.FlexColumnWidth(2),
              2: const pw.FlexColumnWidth(2),
              3: const pw.FlexColumnWidth(1.5),
              4: const pw.FlexColumnWidth(1.5),
            },
            children: [
              // Header
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                children: [
                  _buildPdfTableCell('Nama Goal', isHeader: true),
                  _buildPdfTableCell('Terkumpul', isHeader: true),
                  _buildPdfTableCell('Target', isHeader: true),
                  _buildPdfTableCell('Progress', isHeader: true),
                  _buildPdfTableCell('Status', isHeader: true),
                ],
              ),
              // Data rows
              ...report.goals.map(
                (goal) => pw.TableRow(
                  children: [
                    _buildPdfTableCell(goal.name),
                    _buildPdfTableCell(
                      currencyFormatter.format(goal.currentAmount),
                    ),
                    _buildPdfTableCell(
                      currencyFormatter.format(goal.targetAmount),
                    ),
                    _buildPdfTableCell(
                      '${goal.progressPercentage.toStringAsFixed(1)}%',
                    ),
                    _buildPdfTableCell(goal.status),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfTableCell(String text, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }

  static pw.Widget _buildPdfAchievements(SavingsReport report) {
    return pw.Container(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Pencapaian',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          ...report.achievements.map(
            (achievement) => pw.Container(
              margin: const pw.EdgeInsets.only(bottom: 8),
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                color: PdfColors.amber50,
                borderRadius: pw.BorderRadius.circular(5),
              ),
              child: pw.Row(
                children: [
                  pw.Text(
                    achievement.icon,
                    style: const pw.TextStyle(fontSize: 16),
                  ),
                  pw.SizedBox(width: 10),
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          achievement.title,
                          style: pw.TextStyle(
                            fontSize: 12,
                            fontWeight: pw.FontWeight.bold,
                          ),
                        ),
                        pw.Text(
                          achievement.description,
                          style: pw.TextStyle(
                            fontSize: 10,
                            color: PdfColors.grey600,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfBadges(SavingsReport report) {
    return pw.Container(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Badge yang Diperoleh',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Wrap(
            spacing: 10,
            runSpacing: 10,
            children: report.badges.map((badge) {
              // Determine badge color based on tier
              PdfColor badgeColor;
              switch (badge.displayTier.toLowerCase()) {
                case 'platinum':
                  badgeColor = PdfColors.cyan800;
                  break;
                case 'gold':
                  badgeColor = PdfColors.amber600;
                  break;
                case 'silver':
                  badgeColor = PdfColors.grey600;
                  break;
                default: // bronze
                  badgeColor = PdfColors.brown600;
              }

              return pw.Container(
                width: 130,
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  color: badgeColor.shade(50),
                  borderRadius: pw.BorderRadius.circular(10),
                  border: pw.Border.all(color: badgeColor, width: 2),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.center,
                  children: [
                    pw.Text(
                      badge.icon,
                      style: const pw.TextStyle(fontSize: 24),
                    ),
                    pw.SizedBox(height: 6),
                    pw.Text(
                      badge.name,
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: badgeColor,
                      ),
                      textAlign: pw.TextAlign.center,
                      maxLines: 2,
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      badge.displayTier.toUpperCase(),
                      style: pw.TextStyle(fontSize: 8, color: badgeColor),
                    ),
                  ],
                ),
              );
            }).toList(),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfTips(SavingsReport report) {
    return pw.Container(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Tips Menabung',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          ...report.tips.map(
            (tip) => pw.Container(
              margin: const pw.EdgeInsets.only(bottom: 5),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(tip.icon, style: const pw.TextStyle(fontSize: 12)),
                  pw.SizedBox(width: 8),
                  pw.Expanded(
                    child: pw.Text(
                      tip.tip,
                      style: const pw.TextStyle(fontSize: 11),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfMonthlyBreakdown(SavingsReport report) {
    return pw.Container(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Tren Tabungan Bulanan',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(3),
              2: const pw.FlexColumnWidth(1.5),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                children: [
                  _buildPdfTableCell('Bulan', isHeader: true),
                  _buildPdfTableCell('Total Ditabung', isHeader: true),
                  _buildPdfTableCell('Transaksi', isHeader: true),
                ],
              ),
              ...report.monthlyBreakdown.map(
                (item) => pw.TableRow(
                  children: [
                    _buildPdfTableCell(item.month),
                    _buildPdfTableCell(currencyFormatter.format(item.amount)),
                    _buildPdfTableCell('${item.depositCount}x'),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ===== EXCEL EXPORT =====

  static Future<File> exportToExcel(SavingsReport report) async {
    final excel = Excel.createExcel();

    // Remove default sheet
    excel.delete('Sheet1');

    // Create Summary Sheet
    _createSummarySheet(excel, report);

    // Create Goals Sheet
    _createGoalsSheet(excel, report);

    // Create Monthly Breakdown Sheet
    if (report.monthlyBreakdown.isNotEmpty) {
      _createMonthlySheet(excel, report);
    }

    // Create Transactions Sheet
    if (report.transactions.isNotEmpty) {
      _createTransactionsSheet(excel, report);
    }

    // Create Achievements Sheet
    if (report.achievements.isNotEmpty) {
      _createAchievementsSheet(excel, report);
    }

    // Create Badges Sheet
    if (report.badges.isNotEmpty) {
      _createBadgesSheet(excel, report);
    }

    // Save file
    final directory = await getApplicationDocumentsDirectory();
    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    final file = File('${directory.path}/Laporan_GoalMoney_$timestamp.xlsx');
    await file.writeAsBytes(excel.save()!);

    return file;
  }

  static void _createSummarySheet(Excel excel, SavingsReport report) {
    final sheet = excel['Ringkasan'];

    // Header styling
    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.green300,
      fontColorHex: ExcelColor.white,
      fontSize: 14,
    );

    final labelStyle = CellStyle(bold: true);

    // Title
    sheet.cell(CellIndex.indexByString('A1')).value = TextCellValue(
      'LAPORAN PROGRESS TABUNGAN GOALMONEY',
    );
    sheet.cell(CellIndex.indexByString('A1')).cellStyle = headerStyle;
    sheet.merge(CellIndex.indexByString('A1'), CellIndex.indexByString('D1'));

    // Report info
    sheet.cell(CellIndex.indexByString('A3')).value = TextCellValue(
      'Tanggal Laporan:',
    );
    sheet.cell(CellIndex.indexByString('A3')).cellStyle = labelStyle;
    sheet.cell(CellIndex.indexByString('B3')).value = TextCellValue(
      report.reportDate,
    );

    sheet.cell(CellIndex.indexByString('A4')).value = TextCellValue('Periode:');
    sheet.cell(CellIndex.indexByString('A4')).cellStyle = labelStyle;
    sheet.cell(CellIndex.indexByString('B4')).value = TextCellValue(
      '${report.period.startDate} - ${report.period.endDate}',
    );

    // Summary section
    sheet.cell(CellIndex.indexByString('A6')).value = TextCellValue(
      'RINGKASAN',
    );
    sheet.cell(CellIndex.indexByString('A6')).cellStyle = headerStyle;
    sheet.merge(CellIndex.indexByString('A6'), CellIndex.indexByString('B6'));

    final summaryData = [
      ['Total Goals', report.summary.totalGoals],
      ['Goals Selesai', report.summary.completedGoals],
      ['Goals Aktif', report.summary.activeGoals],
      ['Total Ditabung', currencyFormatter.format(report.summary.totalSaved)],
      ['Total Target', currencyFormatter.format(report.summary.totalTarget)],
      [
        'Sisa Target',
        currencyFormatter.format(
          report.summary.totalTarget - report.summary.totalSaved,
        ),
      ],
      [
        'Progress Keseluruhan',
        '${report.summary.overallProgress.toStringAsFixed(1)}%',
      ],
      ['Total Deposit', report.summary.totalDeposits],
      ['Total Withdrawal', report.summary.totalWithdrawals],
    ];

    for (var i = 0; i < summaryData.length; i++) {
      sheet.cell(CellIndex.indexByString('A${8 + i}')).value = TextCellValue(
        summaryData[i][0].toString(),
      );
      sheet.cell(CellIndex.indexByString('A${8 + i}')).cellStyle = labelStyle;
      final value = summaryData[i][1];
      if (value is int) {
        sheet.cell(CellIndex.indexByString('B${8 + i}')).value = IntCellValue(
          value,
        );
      } else {
        sheet.cell(CellIndex.indexByString('B${8 + i}')).value = TextCellValue(
          value.toString(),
        );
      }
    }

    // Set column widths
    sheet.setColumnWidth(0, 25);
    sheet.setColumnWidth(1, 30);
  }

  static void _createGoalsSheet(Excel excel, SavingsReport report) {
    final sheet = excel['Detail Goals'];

    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.blue300,
      fontColorHex: ExcelColor.white,
    );

    // Headers
    final headers = [
      'No',
      'Nama Goal',
      'Tipe',
      'Target',
      'Terkumpul',
      'Sisa',
      'Progress',
      'Status',
      'Deadline',
      'Total Deposit',
    ];
    for (var i = 0; i < headers.length; i++) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
          .value = TextCellValue(
        headers[i],
      );
      sheet
              .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
              .cellStyle =
          headerStyle;
    }

    // Data rows
    for (var i = 0; i < report.goals.length; i++) {
      final goal = report.goals[i];
      final row = i + 1;

      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
          .value = IntCellValue(
        i + 1,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
          .value = TextCellValue(
        goal.name,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: row))
          .value = TextCellValue(
        goal.type,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 3, rowIndex: row))
          .value = DoubleCellValue(
        goal.targetAmount,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 4, rowIndex: row))
          .value = DoubleCellValue(
        goal.currentAmount,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 5, rowIndex: row))
          .value = DoubleCellValue(
        goal.remainingAmount,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 6, rowIndex: row))
          .value = TextCellValue(
        '${goal.progressPercentage.toStringAsFixed(1)}%',
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 7, rowIndex: row))
          .value = TextCellValue(
        goal.status,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 8, rowIndex: row))
          .value = TextCellValue(
        goal.deadline ?? '-',
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 9, rowIndex: row))
          .value = IntCellValue(
        goal.totalDeposits,
      );
    }

    // Set column widths
    sheet.setColumnWidth(0, 5);
    sheet.setColumnWidth(1, 25);
    sheet.setColumnWidth(2, 10);
    sheet.setColumnWidth(3, 18);
    sheet.setColumnWidth(4, 18);
    sheet.setColumnWidth(5, 18);
    sheet.setColumnWidth(6, 12);
    sheet.setColumnWidth(7, 12);
    sheet.setColumnWidth(8, 15);
    sheet.setColumnWidth(9, 12);
  }

  static void _createMonthlySheet(Excel excel, SavingsReport report) {
    final sheet = excel['Tren Bulanan'];

    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.orange300,
      fontColorHex: ExcelColor.white,
    );

    // Headers
    final headers = [
      'No',
      'Bulan',
      'Tahun',
      'Total Ditabung',
      'Jumlah Transaksi',
    ];
    for (var i = 0; i < headers.length; i++) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
          .value = TextCellValue(
        headers[i],
      );
      sheet
              .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
              .cellStyle =
          headerStyle;
    }

    // Data rows
    for (var i = 0; i < report.monthlyBreakdown.length; i++) {
      final item = report.monthlyBreakdown[i];
      final row = i + 1;

      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
          .value = IntCellValue(
        i + 1,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
          .value = TextCellValue(
        item.month,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: row))
          .value = IntCellValue(
        item.year,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 3, rowIndex: row))
          .value = DoubleCellValue(
        item.amount,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 4, rowIndex: row))
          .value = IntCellValue(
        item.depositCount,
      );
    }

    // Set column widths
    sheet.setColumnWidth(0, 5);
    sheet.setColumnWidth(1, 15);
    sheet.setColumnWidth(2, 10);
    sheet.setColumnWidth(3, 20);
    sheet.setColumnWidth(4, 18);
  }

  static void _createAchievementsSheet(Excel excel, SavingsReport report) {
    final sheet = excel['Pencapaian'];

    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.amber300,
      fontColorHex: ExcelColor.white,
    );

    // Headers
    final headers = ['No', 'Icon', 'Judul', 'Deskripsi'];
    for (var i = 0; i < headers.length; i++) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
          .value = TextCellValue(
        headers[i],
      );
      sheet
              .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
              .cellStyle =
          headerStyle;
    }

    // Data rows
    for (var i = 0; i < report.achievements.length; i++) {
      final achievement = report.achievements[i];
      final row = i + 1;

      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
          .value = IntCellValue(
        i + 1,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
          .value = TextCellValue(
        achievement.icon,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: row))
          .value = TextCellValue(
        achievement.title,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 3, rowIndex: row))
          .value = TextCellValue(
        achievement.description,
      );
    }

    // Set column widths
    sheet.setColumnWidth(0, 5);
    sheet.setColumnWidth(1, 8);
    sheet.setColumnWidth(2, 30);
    sheet.setColumnWidth(3, 50);
  }

  static void _createBadgesSheet(Excel excel, SavingsReport report) {
    final sheet = excel['Badge'];

    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.purple300,
      fontColorHex: ExcelColor.white,
    );

    // Headers
    final headers = [
      'No',
      'Icon',
      'Nama Badge',
      'Deskripsi',
      'Kategori',
      'Tier',
      'Diperoleh',
    ];
    for (var i = 0; i < headers.length; i++) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
          .value = TextCellValue(
        headers[i],
      );
      sheet
              .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
              .cellStyle =
          headerStyle;
    }

    // Data rows
    for (var i = 0; i < report.badges.length; i++) {
      final badge = report.badges[i];
      final row = i + 1;

      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
          .value = IntCellValue(
        i + 1,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
          .value = TextCellValue(
        badge.icon,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: row))
          .value = TextCellValue(
        badge.name,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 3, rowIndex: row))
          .value = TextCellValue(
        badge.description,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 4, rowIndex: row))
          .value = TextCellValue(
        badge.displayCategory,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 5, rowIndex: row))
          .value = TextCellValue(
        badge.displayTier,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 6, rowIndex: row))
          .value = TextCellValue(
        badge.earnedAt,
      );
    }

    // Set column widths
    sheet.setColumnWidth(0, 5);
    sheet.setColumnWidth(1, 8);
    sheet.setColumnWidth(2, 25);
    sheet.setColumnWidth(3, 40);
    sheet.setColumnWidth(4, 15);
    sheet.setColumnWidth(5, 10);
    sheet.setColumnWidth(6, 20);
  }

  static void _createTransactionsSheet(Excel excel, SavingsReport report) {
    final sheet = excel['Riwayat Transaksi'];

    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.teal300,
      fontColorHex: ExcelColor.white,
    );

    // Headers
    final headers = [
      'No',
      'Tanggal',
      'Nama Goal',
      'Jumlah',
      'Metode',
      'Keterangan',
    ];
    for (var i = 0; i < headers.length; i++) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
          .value = TextCellValue(
        headers[i],
      );
      sheet
              .cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
              .cellStyle =
          headerStyle;
    }

    // Data rows
    for (var i = 0; i < report.transactions.length; i++) {
      final t = report.transactions[i];
      final row = i + 1;

      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
          .value = IntCellValue(
        i + 1,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
          .value = TextCellValue(
        t.date,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: row))
          .value = TextCellValue(
        t.goalName,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 3, rowIndex: row))
          .value = DoubleCellValue(
        t.amount,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 4, rowIndex: row))
          .value = TextCellValue(
        t.method,
      );
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 5, rowIndex: row))
          .value = TextCellValue(
        t.description ?? '-',
      );
    }

    // Set column widths
    sheet.setColumnWidth(0, 5);
    sheet.setColumnWidth(1, 20);
    sheet.setColumnWidth(2, 25);
    sheet.setColumnWidth(3, 15);
    sheet.setColumnWidth(4, 15);
    sheet.setColumnWidth(5, 30);
  }

  static pw.Widget _buildPdfTransactions(SavingsReport report) {
    return pw.Container(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Riwayat Transaksi',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(3),
              2: const pw.FlexColumnWidth(2),
              3: const pw.FlexColumnWidth(3),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                children: [
                  _buildPdfTableCell('Tanggal', isHeader: true),
                  _buildPdfTableCell('Goal', isHeader: true),
                  _buildPdfTableCell('Jumlah', isHeader: true),
                  _buildPdfTableCell('Keterangan', isHeader: true),
                ],
              ),
              ...report.transactions.map(
                (t) => pw.TableRow(
                  children: [
                    _buildPdfTableCell(t.date.split(' ')[0]),
                    _buildPdfTableCell(t.goalName),
                    _buildPdfTableCell(currencyFormatter.format(t.amount)),
                    _buildPdfTableCell(t.description ?? '-'),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static Future<File> exportToCsv(SavingsReport report) async {
    final StringBuffer buffer = StringBuffer();

    // Summary Header
    buffer.writeln('RINGKASAN TABUNGAN GOALMONEY');
    buffer.writeln('Tanggal Laporan,${report.reportDate}');
    buffer.writeln(
      'Periode,${report.period.startDate} - ${report.period.endDate}',
    );
    buffer.writeln();

    // Summary Data
    buffer.writeln('Item,Nilai');
    buffer.writeln('Total Goals,${report.summary.totalGoals}');
    buffer.writeln('Goals Selesai,${report.summary.completedGoals}');
    buffer.writeln('Total Ditabung,${report.summary.totalSaved}');
    buffer.writeln('Total Target,${report.summary.totalTarget}');
    buffer.writeln('Progress Keseluruhan,${report.summary.overallProgress}%');
    buffer.writeln();

    // Transactions Header
    buffer.writeln('RIWAYAT TRANSAKSI');
    buffer.writeln('Tanggal,Goal,Jumlah,Metode,Keterangan');

    for (final t in report.transactions) {
      buffer.writeln(
        '"${t.date}","${t.goalName}",${t.amount},"${t.method}","${t.description ?? "-"}"',
      );
    }

    final directory = await getApplicationDocumentsDirectory();
    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    final file = File('${directory.path}/Laporan_GoalMoney_$timestamp.csv');
    await file.writeAsString(buffer.toString());

    return file;
  }

  // ===== UTILITY =====

  static Future<void> openFile(File file) async {
    await OpenFile.open(file.path);
  }
}
